---

name: Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: |
          python -m pip install pytest hypothesis django
          make -C python-initiation test
          make -C python-avance test
          # TODO: The following needs a configured Django:
          # make -C drf-initiation test
          # make -C django-initiation test

  build_and_publish:
    needs: test
    strategy:
      matrix:
        directory:
          - python-initiation
          - python-avance
          - drf-initiation
          - django-initiation
          - python-perfs
          - git-initiation
    secrets:
      deploy_key: ${{ secrets.deploy_key }}
      known_hosts: ${{ secrets.known_hosts }}
    uses: JulienPalard/formations/.github/workflows/deploy.yml@main
    with:
      directory: ${{ matrix.directory }}
