name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish
      env:
        deploy_key: ${{secrets.deploy_key}}
        known_hosts: ${{secrets.known_hosts}}
      run: |
        mkdir -p ${HOME}/.ssh
        printf "%s\n" "$known_hosts" > ${HOME}/.ssh/known_hosts
        printf "%s\n" "$deploy_key" > ${HOME}/.ssh/id_ed25519
        chmod 600 ${HOME}/.ssh/id_ed25519
        eval $(ssh-agent)
        ssh-add
        rm ${HOME}/.ssh/id_ed25519
        export deploy_key=""
        python3 -m pip install --user --upgrade pip
        python3 -m pip install --user mdtoreveal
        export PATH="$HOME/.local/bin/:$PATH"
        make -C initiation rsync
        make -C avancé rsync
        make -C drf-initiation rsync
        make -C django-initiation rsync
