---

name: Publish

on: [push]

jobs:
  publish:
    name: ${{ matrix.directory }}
    strategy:
      matrix:
        directory:
          - python-initiation
          - python-avancé
          - drf-initiation
          - django-initiation
          - python-perfs
          - git-initiation
    secrets:
      deploy_key: ${{ secrets.deploy_key }}
      known_hosts: ${{ secrets.known_hosts }}
    uses: JulienPalard/formations/.github/workflows/deploy.yml@main
    with:
      directory: ${{ matrix.directory }}
